# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Pull request check

on:
  pull_request:

permissions:
  contents: read

jobs:
  check-code:
    runs-on: ubuntu-22.04 # Latest LTS
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
      - name: Set up Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18.16.0'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Run code linting
        run: npm run lint
      - name: Run tests
        run: npm test
      - name: Build project
        run: npm run build
