# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Staging deploy

on:
  push: # On push commits and merge a pull request
    branches: ['dev']

permissions:
  contents: read

# Cannot declare a global env var which contains GITHUB_SHA env var
# Because GITHUB_SHA only available to every step (not job or workflow)
# Cannot use ${GITHUB_SHA::7} as env value, always specify it in a command
# Because the "::7" part only evaluated at runtime, not in an assignment

jobs:
  check-code:
    runs-on: ubuntu-22.04 # Latest LTS
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
      - name: Set up Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18.16.0'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Run code linting
        run: npm run lint
      - name: Run tests
        run: npm test
  build-push-image:
    needs: ['check-code']
    runs-on: ubuntu-22.04 # Latest LTS
    environment:
      name: staging
      url: https://hub.docker.com/r/tonghoangvu/pocketo-web
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
      - name: Build Docker image
        env:
          DOCKER_BUILDKIT: 1
        run: docker image build -t "${{ vars.DOCKER_USERNAME }}/${{ vars.DOCKER_IMAGE_NAME }}:dev-${GITHUB_SHA::7}" .
      - name: Log in to Docker registry
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Push Docker image
        run: docker image push "${{ vars.DOCKER_USERNAME }}/${{ vars.DOCKER_IMAGE_NAME }}:dev-${GITHUB_SHA::7}"
  deploy:
    needs: ['check-code', 'build-push-image']
    runs-on: ubuntu-22.04 # Latest LTS
    environment:
      name: staging
      url: https://app.pocketo.win
    steps:
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v0.1.9
        env:
          SERVER_WORKDIR: ${{ secrets.SERVER_WORKDIR }}
          # Don't combine these env vars into APP_IMAGE, see the reason above
          DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}
          DOCKER_IMAGE_NAME: ${{ vars.DOCKER_IMAGE_NAME }}
          GITHUB_SHA: ${GITHUB_SHA}
        with:
          host: ${{ vars.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          envs: SERVER_WORKDIR, DOCKER_USERNAME, DOCKER_IMAGE_NAME, GITHUB_SHA
          script: |
            cd "${SERVER_WORKDIR}"
            bash ./runner.sh "${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME}:dev-${GITHUB_SHA::7}"
